# -*- coding: utf-8 -*-
"""
/***************************************************************************
 EditionReloader
                                 A QGIS plugin
 Wtyczka służąca do pozyskiwania informacji o edytowanej warstwie z bazy danych w celu wykrywania zmian w zmienianych obiektach.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-06-15
        copyright            : (C) 2021 by EnviroSolutions Sp. z o.o.
        email                : office@envirosolutions.pl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load EditionReloader class from file EditionReloader.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .EditionReloader import EditionReloader
    return EditionReloader(iface)
